### ISSUE TITLE
where to host database?

### ISSUE THREAD

**Issue by joshxfi** [joshxfi/umamin#11]
Currently using [railway.app](https://railway.app/) in production for a PostgreSQL database.

railway (left) vs planetscale (right)

<div align=center>

<img height=500 src="https://user-images.githubusercontent.com/69457996/178473508-a2d8911b-2466-491b-933d-327c1d659758.png" />

<img height=500 src="https://user-images.githubusercontent.com/69457996/178474651-9c7dbe36-0e46-4f57-af69-7465338689a2.png" />

</div>

<hr />

Railway will be nerfing free tier
[Read more](https://blog.railway.app/p/updates-on-plans)

<img width=600 src="https://user-images.githubusercontent.com/69457996/178475489-5a228133-f280-473f-a3a8-8877c8b762ff.png" />

Platnetscale has 1 billion row reads a month + 10 million row writes a month for free.
Should we move to a Vitess/MySQL database w/ planetscale @princejoogie ?

PS: umamin will be free and ad-free so I want to use free tiers.

**Comment by princejoogie** [comment]
yea we can opt for planetscale. its an easy migration our schema is compatible anyways. ill update the docker stuff tomorrow

**Comment by princejoogie** [comment]
also i think plnetscale handles the connection pooling since we use nextjs (serverless api). not sure if railway does

**Comment by joshxfi** [comment]
> yea we can opt for planetscale. its an easy migration our schema is compatible anyways. ill update the docker stuff tomorrow

thanks!
