### ISSUE TITLE
set own password

### ISSUE THREAD

**Issue by princejoogie** [joshxfi/umamin#23]
currently the app generates a random password to use for logging in during the signup process.

i think it is better to let them set it on their own during sign up considering we have no reset password (yet). which would require them to register their email later on.

they can also easily forget or misplace the generated password for them (which i did a few times and had to delete that user from the db)

WDYT? @joshxfi @hyamero

**Comment by joshxfi** [comment]
True, I also misplaced lots of password & I ended up creating new users. 

In the `Success` component, we could add `password` & `confirm password` inputs. & only only add their data once proceed is clicked. I'll work on this later.

ps: scheduled brownout today
