### ISSUE TITLE
css conflict in production

### ISSUE THREAD

**Issue by joshxfi** [joshxfi/umamin#30]
probably caused by the variables in `src/styles/utils.css`

![image](https://user-images.githubusercontent.com/69457996/180194457-3a803595-562c-4d0b-a987-1d63432ee94a.png)

![image](https://user-images.githubusercontent.com/69457996/180194493-07f51521-5439-4ec4-bb50-f5d3ac654856.png)

**Comment by hyamero** [comment]
commit f25afa61b5fcf6ba5bbfa6561c369d19bca84e63 fixes the issue
