### ISSUE TITLE
share button

### ISSUE THREAD

**Issue by princejoogie** [joshxfi/umamin#31]
![image](https://user-images.githubusercontent.com/47204120/180287598-a3223ca1-2aa4-447e-adcc-a7e5a0a5e0ef.png)

- add a share button in each message card
- will export an image of the message card (used to post in ig story etc.)

if possible,
- a share button that directly creates a story instance in instagram

**Comment by hyamero** [comment]
btw there was a css conflict in production, causing ui issues

closed issue (_not merged to dev yet_):
- #30

**Comment by joshxfi** [comment]
currently working on save/export image using [html-to-image](https://github.com/bubkoo/html-to-image) (it is much lighter and faster than [html-to-canvas](https://betterprogramming.pub/heres-why-i-m-replacing-html2canvas-with-html-to-image-in-our-react-app-d8da0b85eadf))

however, for the Instagram stories:
- it only supports android apps officially (https://developers.facebook.com/docs/instagram/sharing-to-stories/)
- content publishing does not support stories (https://developers.facebook.com/docs/instagram-api/guides/content-publishing)

though I found a workaround which I hope will work:
https://stackoverflow.com/a/65893635/14151086
