### ISSUE TITLE
padding is compressed in production

### ISSUE THREAD

**Issue by joshxfi** [joshxfi/umamin#43]
## dev

![image](https://user-images.githubusercontent.com/69457996/180901457-980286d3-c26c-4724-b99d-4ce1f7cad807.png)
![image](https://user-images.githubusercontent.com/69457996/180901461-e9fe125d-256f-4390-ae9a-7a863309c728.png)

## production

![image](https://user-images.githubusercontent.com/69457996/180901356-932885f4-cf04-4fae-838e-ebf199e167f1.png)
![image](https://user-images.githubusercontent.com/69457996/180901360-76a3951d-570f-437f-be07-4d80504c6e3f.png)

**Comment by hyamero** [comment]
commit aea8240f1577a4431336847a159d123b1ec6c35e fixes the issue
