### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by mmmsss211** [joshxfi/umamin#49]
**Bug**
Opening link error

**To Reproduce**
1. Go to '[dashboard](https://dev.umamin.link/inbox)'
2. Copy URL
3. Open URL

**Screenshots**
![image](https://user-images.githubusercontent.com/6498007/180981838-ce859c3e-0f26-4947-9c9d-c85cacce3f96.png)
![image](https://user-images.githubusercontent.com/6498007/180982181-73c8667c-9781-4b27-a219-9d1242e72a30.png)

**Comment by joshxfi** [comment]
Sorry for the confusion, `dev` and `main` branch have different databases, I think that's why it couldn't locate the user. Did u create a user on `dev.umamin.link`? If so the account should be saved at `dev.umamin.link/username`.

**Comment by mmmsss211** [comment]
Thanks for the heads-up master josh 👌
