### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by Kenjix29** [joshxfi/umamin#60]
![Screenshot_20220728-230419](https://user-images.githubusercontent.com/110184282/181571835-b24b64f5-ff9e-441d-a323-e4ae0a4c205a.png)
You are unable to receive a message unless you use original browser.

**Comment by princejoogie** [comment]
are you opening this link via messanger @Kenjix29?

**Comment by princejoogie** [comment]
we use sessions to store user login so it might not work when opening via messenger as it instantiates a new browser

**Comment by hyamero** [comment]
tried opening via messenger, works fine for me. @Kenjix29 can you tell us where you opened the link?

**Comment by Kenjix29** [comment]
> tried opening via messenger, works fine for me. @Kenjix29 can you tell us where you opened the link?

I opened it using facebook

**Comment by hyamero** [comment]
@Kenjix29 are you still experiencing this bug or was it a one-time issue? If you're still experiencing this bug, can you please indicate if you opened it via _facebook app_ or _facebook browser_ or _facebook light_?
