### ISSUE TITLE
di nakikita yung ibang message

### ISSUE THREAD

**Issue by tirdhe** [joshxfi/umamin#70]
di po nakikita yung ibang message
![image](https://user-images.githubusercontent.com/110286847/181916119-8a1c5350-3702-47f3-91fd-41909ebd0653.png)

**Comment by joshxfi** [comment]
hello @tirdhe if you click `more` and no data is showing any more that means that you do not have any more messages. I'm currently working on a fix to avoid confusion, thanks!
