### ISSUE TITLE
umamin bug

### ISSUE THREAD

**Issue by dxzvy** [joshxfi/umamin#72]
**Describe the bug**
it shows that i have 3 umamin messages but i can't view any of them. all of them starts disappearing in a split second after refreshing.

**To Reproduce**

**Expected behavior**
i expect to see my umamin messages after this.

**Screenshots**
![Screenshot_20220730-222535_Chrome](https://user-images.githubusercontent.com/110295506/181918781-8eabd65c-6330-4a46-b00c-0ec95921dd66.jpg)
![Screenshot_20220730-222537_Chrome](https://user-images.githubusercontent.com/110295506/181918798-6e7b0b53-2a2d-4bde-af0e-88d3713822ee.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Samsung Galaxy j4 plus
- Android 
- Chrome
- ver. 9

**Additional context**

**Comment by joshxfi** [comment]
Hello @dxzvy that appears when the page loads to prevent the screen from flickering when fetching data. It seems that I forgot to adjust the number of dummy card to show. Thanks for pointing it out! Will be working on a fix

**Comment by joshxfi** [comment]
fixed! https://github.com/joshxfi/umamin/pull/88/commits/612253804fd9022be31dfdda95e120fe6d330649
