### ISSUE TITLE
Messages problem

### ISSUE THREAD

**Issue by Kinyaomiii** [joshxfi/umamin#77]
**Describe the bug**
I cannot see what anonymous messages me.

**To Reproduce**

**Expected behavior**
Nothing much

**Screenshots**
![7D527EE3-5CC3-4C5F-8C33-AC0DA54C8D0E](https://user-images.githubusercontent.com/110360124/182051103-aec16971-8c30-417c-b83c-ebf9df2202c0.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joshxfi** [comment]
you can refer to https://github.com/joshxfi/umamin/issues/72 thanks!

**Comment by Kinyaomiii** [comment]
Its not working well since day 1
