### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Kinyaomiii** [joshxfi/umamin#85]
**Describe the bug**
i cant read anonymous message. It’s disappearing when Im trying to open it.

**To Reproduce**

**Expected behavior**
I expected it will be fixed as soon as possible. I reported it earlier but its not working.

**Screenshots**
![16F5E5E1-FB2D-4FF3-9AD3-6BCAFD907E7E](https://user-images.githubusercontent.com/110360124/182115591-98d46751-6e54-4caf-bef1-5feb90cc2f7f.png)
![AFE07608-5D60-41FC-9D06-2679C8C95DAC](https://user-images.githubusercontent.com/110360124/182115610-336ccbd8-c8eb-4402-8a33-65197af3c8e2.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 11 pro max]
- OS: [e.g. iOS15.6]
- Browser [e.g. safari]
- Version [e.g. 15.6]

**Additional context**
Its keeping disappearing

**Comment by joshxfi** [comment]
Hello @Kinyaomiii that appears when the page loads to prevent the screen from flickering when clicking more. It seems that I forgot to adjust the number of dummy card to show. Thanks for pointing it out! Will be working on a fix

> https://github.com/joshxfi/umamin/issues/72

**Comment by joshxfi** [comment]
fixed! https://github.com/joshxfi/umamin/pull/88/commits/612253804fd9022be31dfdda95e120fe6d330649
